### ISSUE TITLE
Improve the securityContext recommendation to run each Pod using a unique UID.

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/helm-charts-hardened#230]
To improve the security of the SPIFFE pods it would be great if we can adjust the securityContext recommendation to run with a unique UID. 

Checking many out of the box installations of other charts they are using `runAsUser: 1000`, therefore we should pick some UIDs that are not that commonly used to reduce the chance there is potential overlap with other pods in the cluster.

See below my setup to configure the podSecurityContext for each component.

```yaml
global:
  spire:
    recommendations:
      enabled: true
      namespaceLayout: true
      namespacePSS: true
      priorityClassName: true
      strictMode: true
      securityContexts: true

spire-server:
  podSecurityContext:
    runAsUser: 20000
    runAsGroup: 20000
    fsGroup: 20000

spiffe-csi-driver:
  podSecurityContext:
    runAsUser: 20001
    runAsGroup: 20001
    fsGroup: 20001

spire-agent:
  podSecurityContext:
    runAsUser: 20002
    runAsGroup: 20002
    fsGroup: 20002

spiffe-oidc-discovery-provider:
  podSecurityContext:
    runAsUser: 20003
    runAsGroup: 20003
    fsGroup: 20003
```

> [!Note]
> We should decide on a range of UIDs to use for spire pods, so don't take above example as leading.
