### ISSUE TITLE
upstream cert-manager doesn't have rbac permissions for clusterissuers

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#358]

**Comment by ranjit-se7en** [comment]
#### Adding more context on the problem reported in the `spire` slack channel.


We were trying to use the `spire` helm chart to install the server in K8s using `cert-manager` upstream. We have cert-manager running and using the `AWSPCAClusterIssuer` issuers in our clusters. When we try to use the `AWSPCAClusterIssuer` clusterissuers for the cert-manager upstream, the spire server complains that it couldn't find the issuer.

Below are the clusterissuers.
```
k get awspcaclusterissuer
NAME                           AGE
aws-acm-cluster-issuer         545d
aws-acm-cluster-issuer-ecdsa   545d
```

Upstream Config used in the helm chart installation
```yaml
## @param upstreamAuthority.certManager.issuer_name Defaults to the release name, override if CA is provided outside of the chart
issuer_name: "aws-acm-cluster-issuer-ecdsa"
## @param upstreamAuthority.certManager.issuer_kind Defaults to "Issuer", override if CA is provided outside of the chart
issuer_kind: "AWSPCAClusterIssuer"
## @param upstreamAuthority.certManager.issuer_group Defaults to "cert-manager.io", override if CA is provided outside of the chart
issuer_group: "awspca.cert-manager.io"
## @param upstreamAuthority.certManager.namespace Specify to use a namespace other then the one the chart is installed into
namespace: ""
```

Spire server pod logs captured using debug log level.
```bash
time="2024-05-17T03:38:57Z" level=debug msg="Preparing X509 CA" slot=B subsystem_name=ca_manager
time="2024-05-17T03:38:57Z" level=info msg="Waiting for certificaterequest to be signed" external=false name=spiffe-ca-f5vwn namespace=spire-server plugin_name=cert-manager plugin_type=UpstreamAuthority subsystem_name=catalog
time="2024-05-17T03:38:57Z" level=error msg="Created CertificateRequest has failed" external=false message="issuer could not be found" name=spiffe-ca-f5vwn namespace=spire-server plugin_name=cert-manager plugin_type=UpstreamAuthority reason=Failed subsystem_name=catalog
time="2024-05-17T03:38:57Z" level=debug msg="Optimistically cleaning-up stale CertificateRequests" external=false plugin_name=cert-manager plugin_type=UpstreamAuthority subsystem_name=catalog
time="2024-05-17T03:38:57Z" level=debug msg="Deleting stale CertificateRequest" external=false message="issuer could not be found" name=spiffe-ca-f5vwn namespace=spire-server plugin_name=cert-manager plugin_type=UpstreamAuthority reason=Failed subsystem_name=catalog type=Ready
time="2024-05-17T03:38:57Z" level=error msg="Unable to rotate X509 CA" error="rpc error: code = Internal desc = upstreamauthority(cert-manager): request has failed" subsystem_name=ca_manager
```

We know what the problem is now, since spire deletes the failed CertificateRequests, we captured it using a script and could see the below CertificateRequests. If you notice the issuer name you can see the name `aws-acm-cluster-issuer-ecdsa-ca` , we noticed it charts templates appends the `-ca` to the issuer name [here](https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/charts/spire-server/templates/configmap.yaml#L269-L274). Not sure if this is intended?

```json
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "cert-manager.io/v1",
            "kind": "CertificateRequest",
            "metadata": {
                "creationTimestamp": "2024-05-17T09:08:32Z",
                "generateName": "spiffe-ca-",
                "generation": 1,
                "labels": {
                    "cert-manager.spiffe.io/trust-domain": "abcxz.net"
                },
                "name": "spiffe-ca-4vblx",
                "namespace": "spire-server",
                "resourceVersion": "884971325",
                "uid": "af6c70c9-60b6-4d2d-8c44-c8c5bc23254d"
            },
            "spec": {
                "duration": "24h0m0s",
                "extra": {
                    "authentication.kubernetes.io/pod-name": [
                        "spire-server-0"
                    ],
                    "authentication.kubernetes.io/pod-uid": [
                        "2247bb84-0fa5-4d8c-93ad-50e2e650495d"
                    ]
                },
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:spire-server",
                    "system:authenticated"
                ],
                "isCA": true,
                "issuerRef": {
                    "group": "awspca.cert-manager.io",
                    "kind": "AWSPCAClusterIssuer",
                    "name": "aws-acm-cluster-issuer-ecdsa-ca"
                },
```

We also noticed that the `spire-server-cm` role doesn't have permissions for `clusterissues` and `awspcaclusterissuers` , it's only limited to `certificaterequests` and `issuers` [here](https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/charts/spire-server/templates/roles.yaml#L27-L38).


```yaml
rules:
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificaterequests
      - issuers
    verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
```

#### Solution

We added the permissions for `clusterissuers` and `awspcaclusterissuers`  in the spire-server-r, removed the `-ca` from the configmap, and deployed the chart which was successful 🎉 .

**Comment by kfox1111** [comment]
Some more context to the issue: https://github.com/spiffe/helm-charts/pull/378

Looks like -ca is always being appended, rather then just if issuer is not overridden.

**Comment by kfox1111** [comment]
> clusterissuers and awspcaclusterissuers

Are both really needed for reading by spire rather then just awspcaclusterissuers? Which one did you configure it to point to? We may need to come up with another value for additional permissions.

**Comment by ranjit-se7en** [comment]
I added both of them. However, I believe that people using clusterissuers would also face the same problem.

**Comment by ranjit-se7en** [comment]
Also, I don't understand why the `-ca` is appended even in the overrides. If someone wants to use existing issuers this won't work well as the issuers will mistach.

**Comment by kfox1111** [comment]
> I added both of them. However, I believe that people using clusterissuers would also face the same problem.

Trying to figure out how to fix it in general. If both are needed, we need to figure out a way to let the user specify a list of them. If only one is needed, a string is probably ok.

> Also, I don't understand why the -ca is appended even in the overrides. If someone wants to use existing issuers this won't work well as the issuers will mistach.

Its a bug. we gotta figure out how to fix it without breaking too many things.

**Comment by ranjit-se7en** [comment]
The `clusterissuers` are needed for sure, if any custom issuers are used like `awspcaclusterissuers` we should have a provision to specify them(in helm) and accordingly update the RBAC. Here is a list of all issuers that `cert-manager` supports https://cert-manager.io/docs/configuration/issuers/

**Comment by kfox1111** [comment]
I deployed cert manager in minikube, the aws plugin, made a dummy awspcaclusterissuer. then deployed with:
```
spire-server:
  upstreamAuthority:
    certManager:
      enabled: true
      issuer_name: example
      issuer_kind: AWSPCAClusterIssuer
      issuer_group: awspca.cert-manager.io/v1beta1
```

It creates the certrificate request:
```
NAME              APPROVED   DENIED   READY   ISSUER       REQUESTOR                                    AGE
spiffe-ca-nc4fw                               example-ca   system:serviceaccount:default:spire-server   30s
```

So, I can reproduce the extra -ca added to the name... I don't have access to AWSPCA really though so cant test it further.

I looked through the code in spire though and cant find any references to it actually needing to get/list issuers though with regard to the upstream plugin.

How does it behave/fail if it doesn't have the extra types listed in the role?
