### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS contains credentials instead of path to credentials.json

### ISSUE THREAD

**Issue by arvindth** [spiffe/helm-charts-hardened#492]
[This section of cloud-secret.yaml](https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/charts/spire-server/templates/cloud-secret.yaml#L22) loads the credential material into the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, similar to the `AWS_ACCESS_KEY_ID` and other AWS credentials.

However, the `GOOGLE_APPLICATION_CREDENTIALS` environment variable is [meant to hold the path to the credentials file](https://github.com/spiffe/spire/blob/main/doc/plugin_server_nodeattestor_gcp_iit.md?plain=1#L67) on disk, and not the credential itself.

I've worked around this by mounting the file from the secret myself:
```
    extraVolumes:
      - name: spire-server-cloud
        secret:
          secretName: spire-server-cloud
    extraVolumeMounts:
      - name: spire-server-cloud
        mountPath: /run/spire/secrets/cloud_secrets
        readOnly: true
```
and using the `service_account_file` field to point to the file on disk.

However, I think this has security implications because if you don't use the `service_account_file` override, the server error when trying to load the credentials file from the `GOOGLE_APPLICATION_CREDENTIALS` environment variable dumps the contents to the log, exposing the private key.
