### ISSUE TITLE
plugin copying settings

### ISSUE THREAD

**Issue by kfox1111** [spiffe/helm-charts-hardened#589]
It is hard to load in plugins as they need to be copied into the spire-server/spire-agent containers. They don't always have a shell either, so need a helper to load them. This can be made generic, so its easy to give a list of containers / a binary in the container that are plugins to load and do the heavy lifting for the end user.

**Comment by kheraud** [comment]
To bypass this limitation, I used this initContainer to fetch my custom plugin:

```yaml
spire-server:
  extraVolumes:
    - name: plugin-volume
      emptyDir: {}

  extraVolumeMounts:
    - name: plugin-volume
      mountPath: /plugins

  initContainers:
    - name: download-credential-composer
      image: curlimages/curl:8.17.0
      command:
        - sh
        - -c
        - |
          curl -o /plugins/custom-credential-composer "https://randomstorage.dev.domain.tld/custom-credential-composer"
          chmod 755 /plugins/custom-credential-composer && \
          chown 1000:1000 /plugins/custom-credential-composer
      volumeMounts:
        - name: plugin-volume
          mountPath: /plugins
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

Note that I download it from a webserver as I am iteratively testing but the binary would be better stored in a proper image.

And to edit the spire-server configmap; I struggled to do it with the current chart as it does not expose additional entrypoints. For my tests I ended up using a chart inflator pattern: <https://deepwiki.com/kubernetes-sigs/kustomize/4.2-built-in-generators#helmchartinflationgenerator>
