### ISSUE TITLE
Allow users to set default global resources used when resources for an individual container are not defined

### ISSUE THREAD

**Issue by daescha** [spiffe/helm-charts-hardened#607]
in my deployment of spire I need to set resources for the all the containers I am using, and I use the same values for each. this results in a lot of repitition: 

```yaml
global:
  installAndUpgradeHooks:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
spiffe-oidc-discovery-provider:
  enabled: false
spiffe-csi-driver:
  enabled: false
spire-server:
  controllerManager:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  chown:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
spire-agent:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  socketAlternate:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  fsGroupFix:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
```

what I would like to do instead:

```yaml
global:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

----
## Proposal

add a template to spire-lib:

```yaml
{{/*resources: merge global.resources + <section>.resources*/}}
{{- define "spire-lib.mergeResources" -}}
{{- toYaml (mergeOverwrite (deepCopy .Global.resources) .Section.resources) | trim -}}
{{- end -}}
```

then use wherever resources are defined. example usage:

```yaml
# at charts/spire/charts/spire-agent/templates/daemonset.yaml:195
          resources:
            # new
            {{- include "spire-lib.mergeResources" (dict "Section" .Values.socketAlternate "Global" .Values.global) | nindent 12 }}
            # old
            {{/* {{- toYaml .Values.socketAlternate.resources | nindent 12 }}*/}}
```
