### ISSUE TITLE
tornjak-backend ingress error

### ISSUE THREAD

**Issue by simonostendorf** [spiffe/helm-charts-hardened#69]
When using `spire-server.tornjak.ingress.enabled = true` helm wants to create an ingress with

```
spec:
  rules:
    - host: <>
      http:
        paths:
          - path: <>
            pathType: <>
            backend:
              service:
                name: <>
                port:
                  number: tornjak-srv-http
```
See tornjak ingress template: https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/charts/spire-server/templates/tornjak-ingress.yaml#L26C1-L27C1
See ingress template in spire-lib: https://github.com/spiffe/helm-charts-hardened/blob/main/charts/spire/templates/_spire-lib.tpl#L125

This results in nginx ingress controller errors, because the number has to be an integer and not a string.
